apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: simpleingressrules-reader
rules:
  - apiGroups: ["simpleingresscontroller.k8s.io"]
    resources: ["simpleingressrules"]
    verbs: ["get", "watch", "list"]